version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
      - media_files:/app/media
    environment:
      - FLASK_APP=flask_backend
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/productivity_planner
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=productivity_planner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_files:/app/media
    depends_on:
      - api
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:
  media_files:

networks:
  backend:
    driver: bridge 